# Generated by Django 5.2.10 on 2026-01-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_courier_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gözləyir"),
                    ("processing", "Hazırlanır"),
                    ("assigned", "Kuryer təyin edildi"),
                    ("picked_up", "Götürülüb"),
                    ("in_transit", "Yoldadır"),
                    ("delivered", "Çatdırılıb"),
                    ("cancelled", "Ləğv edildi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
